### ISSUE TITLE
Can't rely on argv.d parameter being set

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/wiki-plugin-register#1]
![image](https://user-images.githubusercontent.com/12127/32422408-f2014fda-c254-11e7-9e69-74aa43f5c6c6.png)

Perhaps we need another parameter or we can parse the required info out of the other parameters.

```
[ { _: {},
    autoseed: false,
    test: false,
    help: false,
    h: false,
    f: true,
    farm: true,
    p: 80,
    port: 80,
    conf: '/etc/init/wiki.conf.json',
    config: '/etc/init/wiki.conf.json',
    cookieSecret: 'm...a',
    '$0': '/usr/local/bin/node /usr/local/bin/wiki',
    admin: { google: '105...852' },
    security_type: 'wiki-security-passportjs',
    google_clientID: '725...nem0.apps.googleusercontent.com',
    google_clientSecret: 'Xf9...FfkQ',
    wikiDomains: 
     { 'asia.wiki.org': {},
       'dork.wiki.org': {},
       'pods.wiki.org': {},
       'fed.wiki': {},
       'video.fed.wiki.org': {},
       'au.fedwikihappening.net': {},
       'forage.ward.fed.wiki.org': {},
       '128.199.166.158': {},
       '158.166.199.128': {} },
    valueOf: undefined,
    root: '/usr/local/lib/node_modules/wiki/node_modules/wiki-server',
    home: 'welcome-visitors',
    data: '/root/.wiki/ward.asia.wiki.org',
    packageDir: '/usr/local/lib/node_modules/wiki/node_modules',
    url: 'http://ward.asia.wiki.org',
    wiki_domain: 'asia.wiki.org',
    client: '/usr/local/lib/node_modules/wiki/node_modules/wiki-client/client',
    db: '/root/.wiki/ward.asia.wiki.org/pages',
    status: '/root/.wiki/ward.asia.wiki.org/status',
    assets: '/root/.wiki/ward.asia.wiki.org/assets',
    recycler: '/root/.wiki/ward.asia.wiki.org/recycle',
    id: '/root/.wiki/ward.asia.wiki.org/status/owner.json',
    uploadLimit: '5mb',
    secure_cookie: false,
    session_duration: 7,
    neighbors: '',
    debug: true,
    database: { type: './page' },
    security_legacy: false } ]
```

**Comment by WardCunningham** [comment]
@paul90, I need your help on this issue. I've tried several ways to get the prefix string that will let me make a new directory in .wiki, however it happens to be bound. I see that you have found your way through to add assets and recycle. I'm trying to add a new site and can't seem to get it right.

**Comment by paul90** [comment]
The parameter `d` is just an alias for `data`. But, it will not be set to what you want, it holds the directory the wiki site is using as its data directory, e.g. to use your example, for `ward.asia.wiki.org`, argv.data is `/root/.wiki/ward.asia.wiki.org`. The `data` parameter used to start the farm, probably just the default, will have been `/root/.wiki`.

The new site you are registering (`original`) will want to have its data directory as `/root/.wiki/original.ward.asia.wiki.org`. This could be achieved by:

``` coffeescript
    wantPath =  path.resolve(argv.data, '..', "#{data.domain}.#{site}")
```
using wantPath in place of `#{argv.d}/#{want}`.

When constructing the directory/file name for the fs calls it is better to use `path.join` rather than hardcoding `/` separator.

**N.B.** I don't see any validation of domain parameter in the server code - the server needs to do the same tests as you are already doing on the client.

**Comment by WardCunningham** [comment]
Thank you. That is the formula I was looking for.

I was seduced by the html5 input validations which aren't, as far as I know, duplicated server-side. My short-term solution is to make this an admin-only service. I pass enough information for the server to look up the exact Register item, reparse the markup, and then reapply all validations of which there should be many.

**Comment by WardCunningham** [comment]
Here is an interesting thought. If I were an owner of a site hosted by you on your server, and if I wanted to write a shell script to create a thousand subdomain sites, I could craft a Register on my site using the permission you have delegated to me and then spoof server-side requests with curl. This doesn't seem all bad. But as a server operator I could see a need to place some limits on this delegation of authority.

**Comment by WardCunningham** [comment]
Fixed as suggested. https://github.com/WardCunningham/wiki-plugin-register/commit/83192763995495e57c39364f45e0b6df9939c32d
