### ISSUE TITLE
Maybe not just admin?

### ISSUE THREAD

**Issue by paul90** [WardCunningham/wiki-plugin-register#3]
https://github.com/WardCunningham/wiki-plugin-register/blob/7c49c7e3e1f4271f780c84d84042003568696af7/server/server.coffee#L20

Maybe have an option to allow a wiki owner to create new wiki in a sub-domain of a wiki they already own.

**Comment by WardCunningham** [comment]
Now available to all site owners. #5, version 0.3.0.
