### ISSUE TITLE
register/settings.json undocumented

### ISSUE THREAD

**Issue by almereyda** [WardCunningham/wiki-plugin-register#4]
When running a fresh wiki with the register plugin, it complains about a missing settings file:

```
caution: ENOENT: no such file or directory, open '/root/.wiki/status/plugin/json/tokens.json'
register settings { [Error: ENOENT: no such file or directory, open '/root/.wiki/status/plugins/register/settings.json'

]
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.wiki/status/plugins/register/settings.json' }
```

about-register-plugin.html also did not reveal any details about how this file can be used.

What do I need to set to become an admin user?

**Comment by WardCunningham** [comment]
We'd like to do more but for testing we create credentials by editing a status file:
```
cat ~/.wiki/foo.localhost/status/plugins/register/settings.json 
{
  "code": "asdf"
}
```
At this point the settings.json file is required but the code is not yet checked.

**Comment by WardCunningham** [comment]
We've abandoned settings. Now all users can make new sites owned by themselves, and soon new sites for friends.
